version: '3.7'
services:
  keosd:
    build:
      context: .
      dockerfile: dockerfile
    command:
    - keosd
    - --http-server-address=0.0.0.0:80
    - --verbose-http-errors
    - --http-validate-host=false
    healthcheck:
      test:
      - CMD
      - cleos
      - --no-auto-keosd
      - wallet
      - list
  nodeos:
    build:
      context: .
      dockerfile: dockerfile
    logging:
      driver: "none"
    healthcheck:
      test:
      - "CMD"
      - "curl"
      - "http://localhost/v1/chain/get_info"
    volumes:
    - ./../:/root/src:ro
    command:
    - bash
    - -c
    - >
      nodeos -e -p eosio
      --plugin eosio::producer_plugin
      --plugin eosio::chain_api_plugin
      --plugin eosio::http_plugin
      --plugin eosio::history_plugin
      --plugin eosio::history_api_plugin
      --data-dir /root/eosio/data
      --config-dir /root/eosio/config
      --access-control-allow-origin='*'
      --contracts-console
      --http-validate-host=false
      --verbose-http-errors
      --filter-on='*'
      --http-server-address=0.0.0.0:80
  conntract_test:
    build:
      context: .
      dockerfile: dockerfile
    links:
    - nodeos
    - keosd
    volumes:
    - ./../:/root/src:ro
    stdin_open: true
    tty: true
    depends_on:
    - nodeos
    - keosd
    working_dir: /root
    command:
    - bash
    - /root/src/integration_test/conntract_test.sh
