FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y \
    wget \
    curl \
    gnupg2

RUN wget -q https://github.com/eosio/eos/releases/download/v1.5.0/eosio_1.5.0-1-ubuntu-18.04_amd64.deb && \
    apt install -y ./eosio_1.5.0-1-ubuntu-18.04_amd64.deb && \
    rm ./eosio_1.5.0-1-ubuntu-18.04_amd64.deb

RUN curl -sL https://deb.nodesource.com/setup_11.x | bash -
RUN apt-get install -y nodejs